---
title: 'InitStartError: wandb プロセスとの通信エラー'
menu:
  support:
    identifier: ja-support-kb-articles-initstarterror_error_communicating_wandb_process
support:
  - experiments
toc_hide: true
type: docs
slug: /ja/support/:filename
---
このエラーは、ライブラリがサーバーにデータを同期するプロセスの起動に問題があることを示しています。

以下の回避策は、特定の環境で問題を解決します。

<Tabs>
<Tab title="Tab">
```python
wandb.init(settings=wandb.Settings(start_method="fork"))
```
</Tab>
<Tab title="Tab">
バージョン `0.13.0` より前のものには、次を使用してください：

```python
wandb.init(settings=wandb.Settings(start_method="thread"))
```
</Tab>
</Tabs>